<a href="https://colab.research.google.com/github/Ganeshprasannamax/Registration-and-Login-system-using-Python-file-handling/blob/main/Tasks_1_Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
z= np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
z= np.zeros((10,10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
"import numpy.info(numpy.add)"

'import numpy.info(numpy.add)'

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [8]:
a=np.arange(20)
a=a[::-1]
print(a)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [9]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [10]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [11]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [12]:
a=np.random.random((3,3,3))
print(a)

[[[0.91849421 0.10371916 0.11153211]
  [0.679825   0.50607857 0.91607729]
  [0.55971405 0.12058723 0.62053746]]

 [[0.31841132 0.46413025 0.23152234]
  [0.23456912 0.27159059 0.39267431]
  [0.41475025 0.24096231 0.07697509]]

 [[0.02886797 0.04673747 0.83275758]
  [0.49848838 0.56886824 0.8533783 ]
  [0.32074384 0.92364524 0.03479558]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [13]:
A=np.random.random((10,10))
Amin,Amax =A.min(),A.max()
print(Amin,Amax)

0.0018847437400003608 0.9903907443460435


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [14]:
a=np.random.random(30)
b=a.mean()
print(b)

0.48314997531407966


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [15]:
a=np.ones((10,10))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [16]:
a=np.ones((3,3))
a=np.pad(a, pad_width=1,mode='constant',constant_values=0)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [17]:
a=np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [18]:
arr=np.ones(64,dtype=int)
arr[::2]=0
arr=arr.reshape((8,8))
print(arr)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [19]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [20]:
a=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [21]:
a=np.random.random((5,5))
a=(a-np.mean(a))/(np.std(z))
print(a)

[[ inf  inf -inf  inf  inf]
 [-inf -inf  inf -inf -inf]
 [ inf  inf -inf  inf -inf]
 [ inf -inf -inf -inf  inf]
 [ inf -inf -inf -inf -inf]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [22]:
color=np.dtype([('r',np.ubyte),
                ('g',np.ubyte),
                ('b',np.ubyte),
                ('a',np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [23]:
a=np.dot(np.ones((5,3)),np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [24]:
a=np.arange(11)
a[(3<a)&(a<8)]*=-1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [25]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [26]:
z**z
z <- z
1j*z
z/1/1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [27]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [28]:
a=np.random.uniform(-10,+10,10)
print(np.where(a>0,np.ceil(a),np.floor(a)))

[10.  1.  8. -6.  5.  5. -3.  9.  7.  2.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [29]:
a1=np.random.randint(0,10,10)
a2=np.random.randint(0,10,10)
print(np.intersect1d(a1,a2))

[1 4 5 6 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [30]:
defaults=np.seterr(all='ignore')
a=np.ones(1)/0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [31]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [32]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2022-11-03
2022-11-04
2022-11-05


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [33]:
a = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [34]:
A=np.ones(3)*1
B = np.ones(3)*1
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1., -1., -1.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [35]:
a=np.random.uniform(0,10,10)
print(a-a%1)
print(a//1)
print(np.floor(a))
print(a.astype(int))
print(np.trunc(a))

[5. 9. 1. 0. 7. 6. 5. 4. 8. 1.]
[5. 9. 1. 0. 7. 6. 5. 4. 8. 1.]
[5. 9. 1. 0. 7. 6. 5. 4. 8. 1.]
[5 9 1 0 7 6 5 4 8 1]
[5. 9. 1. 0. 7. 6. 5. 4. 8. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [36]:
a=np.zeros((5,5))
a=a+np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [37]:
def generate():
  for x in range(10):
    yield x
a=np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [38]:
a=np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [39]:
a=np.random.random(10)
a.sort()
print(a)

[0.06493299 0.08266616 0.12036395 0.30744662 0.31699579 0.44427043
 0.4543708  0.64273638 0.64569451 0.7904425 ]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [40]:
a=np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [41]:
a=np.random.randint(0,2,5)
b=np.random.randint(0,2,5)
equal=np.allclose(a,b)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [42]:
a=np.zeros(10)
a.flags.writeable = True
a[0] = 1 

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [43]:
a=np.random.random((10,2))
x,y=a[:,0],a[:,1]
b=np.sqrt(x**2+y**2)
c=np.arctan2(x,y)
print(b)
print(c)

[0.39385623 1.04052239 0.44383297 0.94905373 0.47800672 1.14582125
 0.86926117 0.24776184 1.18107627 0.07379633]
[1.16742877 0.6076332  0.689015   1.05005427 0.86894057 0.77229794
 0.52908707 0.6127245  0.78707662 1.4380422 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [44]:
a=np.random.random(10)
a[a.argmax()]=0
print(a)

[0.08858126 0.36690427 0.40637046 0.14181088 0.         0.15217553
 0.54116819 0.76087435 0.13478909 0.5029954 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [45]:
a=np.zeros((5,5),[('x',float),('y',float)])
a['x'],a['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [46]:
a=np.arange(8)
b=a+0.5
c=1.0/np.subtract.outer(a,b)
print(np.linalg.det(c))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [47]:
for dtype in[np.int8,np.int32,np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in[np.float32,np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [48]:
np.set_printoptions(threshold=float('inf'))
a=np.zeros((10,10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [49]:
a=np.arange(100)
b=np.random.uniform(0,100)
index=(np.abs(a-b)).argmin()
print(a[index])

79


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [50]:
a=np.zeros(10,[('position', [('x',float,1),
                            ('y',float,1)]),
              ('color',[('r',float,1),
                        ('g',float,1),
                        ('b',float,1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [51]:
import scipy
import scipy.spatial

a=np.random.random((10,2))
b=scipy.spatial.distance.cdist(a,a)
print(b)

[[0.         0.76012736 0.33136916 0.61301545 0.63875167 0.93248744
  0.37931597 0.47046611 0.93583817 0.67193706]
 [0.76012736 0.         0.84225838 0.46319148 0.1929731  0.38545485
  0.52305326 0.29495625 0.4817623  0.52774331]
 [0.33136916 0.84225838 0.         0.86418007 0.79134782 0.86968766
  0.64824756 0.61116987 0.83123567 0.52323935]
 [0.61301545 0.46319148 0.86418007 0.         0.27392815 0.83300928
  0.2340296  0.33020676 0.91036928 0.82913478]
 [0.63875167 0.1929731  0.79134782 0.27392815 0.         0.56006312
  0.34465053 0.18120355 0.64213985 0.60648463]
 [0.93248744 0.38545485 0.86968766 0.83300928 0.56006312 0.
  0.82963477 0.56850618 0.11758304 0.36962726]
 [0.37931597 0.52305326 0.64824756 0.2340296  0.34465053 0.82963477
  0.         0.26115917 0.88042301 0.72238112]
 [0.47046611 0.29495625 0.61116987 0.33020676 0.18120355 0.56850618
  0.26115917 0.         0.62156502 0.50001319]
 [0.93583817 0.4817623  0.83123567 0.91036928 0.64213985 0.11758304
  0.88042301 0.62156

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [52]:
a=(np.random.rand(10)*100).astype(np.float32)
b=a.view(np.int32)
b[:]=a
print(y)

[0.1545956  0.85427053 0.34258252 0.47217698 0.30861832 0.82076219
 0.75040555 0.20269004 0.83374411 0.00976802]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [53]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
 ''')
a=np.genfromtxt(s,delimiter=',',dtype=np.int)
print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [54]:
a=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(a):
  print(index,value)
for index in np.ndindex(a.shape):
  print(index,a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [55]:
x,y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
a=np.sqrt(x*x+y*y)
sigma,mu=1.0,0.0
b=np.exp(-((a-mu)**2/(2.0*sigma**2)))
print(b)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [56]:
n=10
p=3
a=np.zeros((n,n))
np.put(a,np.random.choice(range(n*n),p,replace=False),1)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [57]:
a=np.random.rand(5,10)
b=a-a.mean(axis=1,keepdims=True)
print(b)

[[-0.38759172  0.27344345  0.24297619  0.30295677  0.30155946 -0.13404864
  -0.40875951  0.29726058 -0.59216823  0.10437165]
 [-0.28856468 -0.46942564  0.44611228  0.03163614  0.15001652  0.42547335
  -0.30862886 -0.45351681  0.21710064  0.24979706]
 [-0.38254691 -0.13288467  0.31766732 -0.06990326  0.5098893  -0.25866421
   0.07882745  0.18849815 -0.22292154 -0.02796162]
 [ 0.20457405 -0.25197953  0.25899959  0.42967522  0.14800675 -0.19050992
  -0.36047326  0.01224475  0.06818341 -0.31872105]
 [ 0.5162319   0.03571281 -0.30977779  0.17636488  0.42361135  0.09727659
  -0.35451608 -0.35387301  0.14866406 -0.37969473]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [58]:
a=np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[5 1 7]
 [6 3 3]
 [4 3 6]]
[[5 1 7]
 [6 3 3]
 [4 3 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [59]:
a=np.random.randint(0,3,(3,10))
print((~a.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [60]:
A=np.random.uniform(0,1,10)
a=0.5
m=A.flat[np.abs(A-a).argmin()]
print(m)

0.4967099395287685


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [61]:
a=np.arange(3).reshape(3,1)
b=np.arange(3).reshape(1,3)
it=np.nditer([a,b,None])
for x,y,z in it:z[...]=x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [62]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [63]:
a=np.ones(10)
b=np.random.randint(0,len(a),20)
a+=np.bincount(b,minlength=len(a))
print(a)

[4. 3. 2. 3. 3. 3. 2. 4. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [64]:
a=[1,2,3,4,5,6]
b=[1,2,4,5,7,1]
F=np.bincount(b,a)
print(F)

[0. 7. 2. 0. 3. 4. 0. 5.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [65]:
w,h=256,256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)
I24 = np.dot(I.astype(np.uint32),[1,256,65536])
n=len(np.unique(I24))
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [66]:
a=np.random.randint(0,10,(3,4,3,4))
sum=a.sum(axis=(-2,-1))
print(sum)

[[62 63 40 50]
 [50 59 48 35]
 [41 51 72 56]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [67]:
D=np.random.uniform(0,1,100)
S=np.random.randint(0,1,100)
D_sums=np.bincount(S,weights=D)
D_counts=np.bincount(S)
D_means=D_sums/D_counts
print(D_means)

[0.49881757]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [68]:
A=np.random.uniform(0,1,(5,5))
B=np.random.uniform(0,1,(5,5))
np.diag(np.dot(A,B))
np.sum(A*B.T,axis=1)

array([1.5394336 , 0.91939913, 0.19848841, 1.91743804, 1.5431094 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [69]:
a=np.array([1,2,3,4,5])
nz=3
a1=np.zeros(len(a)+(len(a)-1)*(nz))
a1[::nz+1]=print(a1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [70]:
x=np.ones((5,5,3))
y=2*np.ones((5,5))
print(x*y[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [71]:
a=np.arange(25).reshape(5,5)
a[[0,1]]=a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [72]:
face=np.random.randint(0,100,(10,3))
F=np.roll(face.repeat(2,axis=1),-1,axis=1)
F=F.reshape(len(F)*3,2)
F=np.sort(F,axis=1)
G=F.view(dtype=[('p0',F.dtype),('p1',F.dtype)])
G=np.unique(G)
print(G)

[( 4, 65) ( 4, 97) (11, 26) (11, 30) (11, 33) (11, 55) (15, 43) (15, 83)
 (16, 28) (16, 82) (18, 62) (18, 74) (25, 29) (25, 69) (26, 55) (28, 82)
 (29, 69) (30, 33) (36, 38) (36, 71) (38, 71) (38, 81) (43, 83) (48, 53)
 (48, 77) (53, 77) (62, 74) (65, 97) (71, 81)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [73]:
c=np.bincount([1,1,2,3,4,4,6])
a=np.repeat(np.arange(len(c)),c)
print(a)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [74]:
def moving_average(a,n=3):
  ret=np.cumsum(a,dtype=float)
  ret[n:]=ret[n:]-ret[:-n]
  return ret[n-1:]/n
a=np.arange(20)
print(moving_average(a,n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [75]:
from numpy.lib import stride_tricks

def rolling(a,window):
  shape=(a.size - window +1, window)
  strides = (a.strides[0],a.strides[0])
  return stride_tricks.as_strided(a, shape=shape, strides=strides)

a=rolling (np.arange(10),3)
print(a)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [76]:
a=np.random.randint(0,2,100)
np.logical_not(a,out=a)

a=np.random.uniform(-1.0,1.0,100)
np.negative(a,out=a)

array([-0.23560648, -0.44653659, -0.24798087, -0.28634212, -0.41017705,
       -0.66612222, -0.74932743,  0.22425968, -0.71498907,  0.60066556,
        0.20978153,  0.73271116, -0.25641888, -0.86227529, -0.56581317,
       -0.34690946, -0.64543354,  0.80116706, -0.15040691,  0.5509974 ,
        0.82703862,  0.93428176,  0.37879305, -0.01913953, -0.76266465,
        0.49897124, -0.25000403,  0.73929819,  0.55748159, -0.06928031,
       -0.21824719, -0.17836679,  0.74511765,  0.97831354,  0.61812671,
       -0.99944095,  0.2148376 ,  0.93556039,  0.66000473, -0.27452739,
       -0.54659347,  0.77180512,  0.08716826,  0.51153763, -0.98883547,
        0.40045769, -0.86287718, -0.54646522, -0.74971155,  0.44250823,
       -0.87984259, -0.92653383,  0.2581538 ,  0.28754209, -0.13344471,
        0.87674279,  0.11683479,  0.44910649, -0.56800522, -0.63389865,
       -0.28829003,  0.42708498, -0.89288527,  0.62216081,  0.58427342,
        0.78809048, -0.2061242 , -0.04490576, -0.22957753,  0.82

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [77]:
def distance(p0,p1,p):
  T=p1 -p0
  L=(T**2).sum(axis=1)
  U=-((p0[:,0]-p[...,0])*T[:,0]+(p0[:,1]-p[...,1])*T[:,1])/L
  U=U.reshape(len(U),1)
  D= p0 + U*T -p
  return np.sqrt((D**2).sum(axis=1))


p0=np.random.uniform(-10,10,(10,2))
p1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(1,2))
print(distance(p0,p1,p))

[11.03885212 14.65913587  1.20361294  3.16008193  8.97136744  4.62291836
  9.33075718  2.51876061  6.70215613  6.76684508]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [78]:
p0=np.random.uniform(-10,10,(10,2))
p1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(10,2))
print(np.array([distance(p0,p1,p_i)for p_i in p]))

[[ 9.62916838  6.27188493 12.70487023  7.8164102   0.29455264 13.98159187
   1.15604868  1.36352245 11.55732676 16.43239549]
 [ 8.37002581  7.2909728   2.1621764   4.77656533  1.85926794  0.38784526
   7.74784529  6.41533069  1.77839466  5.31048609]
 [ 9.1920179   6.26685518  1.43232387  4.52256886  1.02275693  0.78921423
   7.88995228  6.86462019  0.74186789  6.39769483]
 [ 1.88765228  1.96355125 11.94879198 10.85442507  8.04673847 15.97650175
   6.55307686  5.42192582  7.02260109 10.4007626 ]
 [ 2.9306448  11.88974881  4.49500775  4.24110623  7.34327193  0.08883859
   5.15099594  2.39984665  6.50398596  0.1666118 ]
 [ 8.28510849  3.12396684  9.82253394  5.90196422  1.6971574  11.73096937
   0.26791472  1.33398562  8.41935465 13.493034  ]
 [ 2.25283928 16.1194135   6.54297804  3.57540496 12.56567106  0.03079732
   2.56014052  1.49983507 10.85763486  5.26559715]
 [ 5.99465781  3.04083049 10.96473424  8.01320487  3.96261725 13.61058546
   2.7708938   1.24384094  8.24478339 12.6479352 ]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [79]:
A=np.random.uniform(-10,10,(10,2))
shape=(5,5)
fill=0
position=(1,1)

R=np.ones(shape,dtype=z.dtype)*fill
P=np.array(list(position)).astype(int)
Rs=np.array(list(R.shape)).astype(int)
As=np.array(list(A.shape)).astype(int)

R_start=np.zeros((len(shape),)).astype(int)
R_stop=np.zeros((len(shape),)).astype(int)
A_start=(P-Rs//2)
A_stop=(P+Rs//2)+Rs%2

R_start=(R_start-np.minimum(A_start,0)).tolist()
A_start=(np.minimum(A_start,0)).tolist()
R_stop=np.minimum(R_start,(R_stop-np.minimum(A_stop-As,0))).tolist()
A_stop=(np.minimum(A_stop,As)).tolist()

r=[slice(start,stop) for start,stop in zip(R_start,R_stop)]
a=[slice(start,stop) for start,stop in zip(A_start,A_stop)]
R[r] = A[a]
print(A)
print(R)

[[-1.82988082  0.78979962]
 [ 0.73784079 -1.23406429]
 [-4.59354393  2.86068612]
 [-3.92556067 -7.73260938]
 [ 8.98343169 -5.55869181]
 [-5.73197378  8.01202053]
 [-0.14891104  4.47616187]
 [-6.12394868 -6.84652511]
 [-6.16290495 -2.565109  ]
 [ 2.97987422 -6.19348542]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [80]:
A = np.arange(1,15,dtype=np.uint32)
R=stride_tricks.as_strided(A,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [81]:
A = np.random.uniform(0,1,(10,10))
U,S,V = np.linalg.svd(A)
rank=np.linalg.matrix_rank(A)
print(A)

[[0.79645939 0.67613707 0.49686441 0.37000845 0.83231717 0.52433443
  0.5199946  0.90832576 0.01230392 0.85615941]
 [0.20819081 0.86352682 0.01797283 0.49639392 0.24934787 0.72718385
  0.5561201  0.61168714 0.2210685  0.09965485]
 [0.17743024 0.70012009 0.66621492 0.23138208 0.23456133 0.24575466
  0.98053179 0.14862315 0.83588591 0.32050207]
 [0.13654357 0.53955159 0.71371234 0.20913294 0.52697075 0.1330877
  0.32577611 0.24439743 0.24578883 0.82023447]
 [0.19388468 0.78597352 0.60973849 0.70181801 0.81244485 0.07561979
  0.58834628 0.16951962 0.17104944 0.69064499]
 [0.34723559 0.5318903  0.99721    0.87697443 0.35639298 0.54061093
  0.14140998 0.58194633 0.19289016 0.26998209]
 [0.67431533 0.45921267 0.77938426 0.20765093 0.78171511 0.97293874
  0.42299458 0.44232342 0.58657619 0.61769027]
 [0.9176471  0.65980806 0.16655643 0.35592245 0.11640229 0.27282143
  0.58844524 0.28417315 0.80722091 0.73886175]
 [0.19832481 0.54410866 0.37228401 0.90492915 0.33746207 0.63708747
  0.11324965 

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [82]:
A = np.random.randint(0,10,50)
print(np.bincount(A).argmax())

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [83]:
a=np.random.randint(0,5,(10,10))
n=3
i=1+(a.shape[0]-3)
j=1+(a.shape[1]-3)
C=stride_tricks.as_strided(a,shape=(i,j,n,n),strides=a.strides+a.strides)
print(C)

[[[[1 2 3]
   [0 2 2]
   [4 3 1]]

  [[2 3 4]
   [2 2 3]
   [3 1 3]]

  [[3 4 2]
   [2 3 2]
   [1 3 0]]

  [[4 2 2]
   [3 2 1]
   [3 0 0]]

  [[2 2 0]
   [2 1 4]
   [0 0 1]]

  [[2 0 2]
   [1 4 1]
   [0 1 1]]

  [[0 2 2]
   [4 1 0]
   [1 1 1]]

  [[2 2 2]
   [1 0 0]
   [1 1 0]]]


 [[[0 2 2]
   [4 3 1]
   [2 4 2]]

  [[2 2 3]
   [3 1 3]
   [4 2 2]]

  [[2 3 2]
   [1 3 0]
   [2 2 2]]

  [[3 2 1]
   [3 0 0]
   [2 2 0]]

  [[2 1 4]
   [0 0 1]
   [2 0 0]]

  [[1 4 1]
   [0 1 1]
   [0 0 1]]

  [[4 1 0]
   [1 1 1]
   [0 1 2]]

  [[1 0 0]
   [1 1 0]
   [1 2 4]]]


 [[[4 3 1]
   [2 4 2]
   [2 1 4]]

  [[3 1 3]
   [4 2 2]
   [1 4 1]]

  [[1 3 0]
   [2 2 2]
   [4 1 3]]

  [[3 0 0]
   [2 2 0]
   [1 3 0]]

  [[0 0 1]
   [2 0 0]
   [3 0 1]]

  [[0 1 1]
   [0 0 1]
   [0 1 3]]

  [[1 1 1]
   [0 1 2]
   [1 3 0]]

  [[1 1 0]
   [1 2 4]
   [3 0 0]]]


 [[[2 4 2]
   [2 1 4]
   [1 1 0]]

  [[4 2 2]
   [1 4 1]
   [1 0 3]]

  [[2 2 2]
   [4 1 3]
   [0 3 1]]

  [[2 2 0]
   [1 3 0]
   [3 1 3]]

  [[2 0 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [84]:
class Symetric(np.ndarray):
  def _setitem_(self,index,value):
    i,j = index
    super(Symetric,self)._setitem_((i,j),value)
    super(Symetric,self)._setitem_((j,i),value)

def symetric(A):
  return np.asarray(A + A.T - np.diag(A.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7 11  8  2 13]
 [11  9  7  5 11]
 [ 8  7  7 42 14]
 [ 2  5  4  7  5]
 [13 11 14  5  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [85]:
p,n = 10,20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = tensordot(M,V,axes=[[0,2],[0,1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [86]:
A=np.ones((16,16))
k=4
S=np.add.reduceat(np.add.reduceat(A,np.arange(0,A.shape[0],k), axis=0),
                                     np.arange(0,A.shape[1],k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [87]:
def iterate(Z):
   
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

   
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
  0 0 1 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  0 1 0 0 0 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
  0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [88]:
A = np.arange(1000)
np.random.shuffle(A)
n=5
print(A[np.argpartition(-A,n)][:n])

[999 998 996 997 995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [89]:
def cartesion(arrays):
  arrays = [np.asarray(a) for a in arrays]
  shape = (len(x) for x in arrays)

  ix = np.indices(shape,dtype=int)
  ix = ix.reshape(len(arrays), -1).T

  for n, arr in enumerate(arrays):
    ix[:,n] = arrays[n][ix[:,n]]
    return ix

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [90]:
a=np.array([('hello',2.5,3),
            ('world',3.6,2)])
R=np.core.records.fromarrays(a.T,
                             names='col1,col2,col3',
                             formats='S8,f8,i8')
print(R)

[(b'hello', 2.5, 3) (b'world', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [91]:
x=np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.99 s ± 463 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
143 ms ± 767 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
125 ms ± 631 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [92]:
A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))

C=(A[...,np.newaxis,np.newaxis] ==B)
rows = np.where (C.any((3,1)).all(1))[0]
print(rows)

[2 3 4]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [93]:
A=np.random.randint(0,5,(10,3))
print(A)


[[3 3 2]
 [1 2 1]
 [2 0 1]
 [3 1 1]
 [2 4 0]
 [1 4 3]
 [2 0 4]
 [1 2 1]
 [1 3 1]
 [3 4 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [94]:
I = np.array([0,1,2,3,15,16,32,64,128],dtype=np.uint8)
print(np.unpackbits(I[:,np.newaxis],axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [95]:
a=np.random.randint(0,2,(6,3))
uZ= np.unique(A,axis=0)
print(uZ)

[[1 2 1]
 [1 3 1]
 [1 4 3]
 [2 0 1]
 [2 0 4]
 [2 4 0]
 [3 1 1]
 [3 3 2]
 [3 4 3]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [96]:
A = np.random.uniform(0,1,8)
B = np.random.uniform(0,1,8)

np.einsum('i->',A) #sum(A)
np.einsum('i,i->i',A,B) #A*B
np.einsum('i,i',A,B) #inner(A,B)
np.einsum('i,j->ij',A,B) #outer(A,B)

array([[0.34706735, 0.19824716, 0.45284716, 0.22355591, 0.48673362,
        0.69742511, 0.59080521, 0.32381939],
       [0.09182787, 0.05245268, 0.11981533, 0.05914893, 0.12878109,
        0.18452632, 0.15631658, 0.08567687],
       [0.35028561, 0.20008545, 0.45704628, 0.22562888, 0.49124697,
        0.70389214, 0.59628359, 0.32682208],
       [0.09201618, 0.05256025, 0.12006104, 0.05927023, 0.12904518,
        0.18490473, 0.15663715, 0.08585257],
       [0.22907716, 0.13085038, 0.29889571, 0.14755509, 0.32126202,
        0.46032611, 0.38995308, 0.21373266],
       [0.24495233, 0.13991838, 0.31960933, 0.15778073, 0.34352564,
        0.49222695, 0.41697703, 0.22854444],
       [0.36568275, 0.20888039, 0.47713619, 0.23554661, 0.5128402 ,
        0.73483239, 0.6224938 , 0.34118786],
       [0.26878617, 0.15353243, 0.3507073 , 0.17313279, 0.37695066,
        0.5401206 , 0.45754886, 0.2507818 ]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [97]:
phi=np.arange(0,10*np.pi,0.1)
a=1
x=a*phi*np.cos(phi)
y=a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0,r.max(),200)
x_int = np.interp(r_int,r,x)
y_int = np.interp(r_int,r,y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [98]:
x = np.asarray([[1.0,0.0,3.0,8.0],
                [2.0,0.0,1.0,1.0],
                [1.5,2.5,1.0,0.0]])

n=4
M = np.logical_and.reduce(np.mod(x,1)==0,axis=-1)
M &= (x.sum(axis=-1) ==n)
print(x[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [99]:
x = np.random.randn(100)
n = 1000
idx = np.random.randint(0,x.size,(n,x.size))
means = x[idx].mean(axis=1)
confint = np.percentile(means,[2.5,97.5])
print(confint)

[-0.26270983  0.08894839]
